// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_DexterStephens.Models;

namespace Mission6_DexterStephens.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_DexterStephens.Models.Home.MovieModel", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Title = "Dark Knight",
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Year = 2008
                        },
                        new
                        {
                            Title = "Cars",
                            Category = "Action/Adventure",
                            Director = "John Lasseter",
                            Edited = false,
                            Rating = "G",
                            Year = 2006
                        },
                        new
                        {
                            Title = "Harry Potter and the Chamber of Secrets",
                            Category = "Action/Adventure",
                            Director = "Chris Columbus",
                            Edited = false,
                            Rating = "PG",
                            Year = 2002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
